"""update task

Revision ID: 29d4d9705225
Revises: f8a9b0c1d2e3
Create Date: 2026-05-28 19:50:20.854626

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '29d4d9705225'
down_revision = 'f8a9b0c1d2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('ai_built', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('task', sa.Column('ai_build_started', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'ai_build_started')
    op.drop_column('task', 'ai_built')
    # ### end Alembic commands ###
