"""add privacy policy fields to user

Revision ID: 43a838dff679
Revises: a8b9c0d1e2f3
Create Date: 2026-05-03 07:15:27.389188

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '43a838dff679'
down_revision = 'a8b9c0d1e2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_group_id'), table_name='task')
    op.drop_index(op.f('ix_task_parent_id'), table_name='task')
    op.drop_index(op.f('ix_task_log_task_id_timestamp'), table_name='task_log')
    op.drop_index(op.f('ix_task_log_task_id_type'), table_name='task_log')

    # Add privacy policy fields with default value False for existing users
    op.add_column('user', sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('privacy_policy_accepted_at', sa.DateTime(), nullable=True))

    # Remove server_default after adding the column (so new rows don't get auto-default)
    op.alter_column('user', 'privacy_policy_accepted', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'privacy_policy_accepted_at')
    op.drop_column('user', 'privacy_policy_accepted')
    op.create_index(op.f('ix_task_log_task_id_type'), 'task_log', ['task_id', 'type'], unique=False)
    op.create_index(op.f('ix_task_log_task_id_timestamp'), 'task_log', ['task_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_task_parent_id'), 'task', ['parent_id'], unique=False)
    op.create_index(op.f('ix_task_group_id'), 'task', ['group_id'], unique=False)
    # ### end Alembic commands ###
